// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEMuV7Q8jJpLmsdSVChBuJfPmgOg_la-k',
    appId: '1:881325689547:web:49cfb7e848c1631ab5294e',
    messagingSenderId: '881325689547',
    projectId: 'flash-chat-flutter-2025-14414',
    authDomain: 'flash-chat-flutter-2025-14414.firebaseapp.com',
    storageBucket: 'flash-chat-flutter-2025-14414.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRtwxPtsVQI2bEJThnVA9w7muH_CygPQI',
    appId: '1:881325689547:android:ffcd5bc28c879ee6b5294e',
    messagingSenderId: '881325689547',
    projectId: 'flash-chat-flutter-2025-14414',
    storageBucket: 'flash-chat-flutter-2025-14414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf3YjT63p0YKXa6qmp8P9Xl9f5qcBrX4Y',
    appId: '1:881325689547:ios:778f763e5b528234b5294e',
    messagingSenderId: '881325689547',
    projectId: 'flash-chat-flutter-2025-14414',
    storageBucket: 'flash-chat-flutter-2025-14414.firebasestorage.app',
    iosBundleId: 'com.example.flashChatFlutter2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf3YjT63p0YKXa6qmp8P9Xl9f5qcBrX4Y',
    appId: '1:881325689547:ios:778f763e5b528234b5294e',
    messagingSenderId: '881325689547',
    projectId: 'flash-chat-flutter-2025-14414',
    storageBucket: 'flash-chat-flutter-2025-14414.firebasestorage.app',
    iosBundleId: 'com.example.flashChatFlutter2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEMuV7Q8jJpLmsdSVChBuJfPmgOg_la-k',
    appId: '1:881325689547:web:cf762dd8d71bcad9b5294e',
    messagingSenderId: '881325689547',
    projectId: 'flash-chat-flutter-2025-14414',
    authDomain: 'flash-chat-flutter-2025-14414.firebaseapp.com',
    storageBucket: 'flash-chat-flutter-2025-14414.firebasestorage.app',
  );
}
